module.exports = [
  {
    ignores: ['node_modules/**', 'server/node_modules/**', 'coverage/**', 'server/db/backups/**', 'server/uploads/**'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        importScripts: 'readonly',
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        Buffer: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        URLSearchParams: 'readonly',
        history: 'readonly',
        IntersectionObserver: 'readonly',
        CustomEvent: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        APP_SHELL: 'readonly',
        getElementSection: 'readonly',
        initGlobalLookup: 'readonly',
        initPrintTools: 'readonly',
        switchSection: 'readonly',
        getCardTitle: 'readonly',
        setActiveSection: 'readonly',
        scrollToTarget: 'readonly',
        escapeHtmlPrint: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'off',
      'no-empty': 'off',
    },
  },
];
