const { execFileSync } = require('child_process');
const { readFileSync, existsSync } = require('fs');
const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');

function getOptionalBetterSqlite3() {
  try {
    const Database = require('better-sqlite3');
    const probe = new Database(':memory:');
    probe.close();
    return Database;
  } catch (error) {
    if (error.code === 'MODULE_NOT_FOUND' || /Could not locate the bindings file/.test(error.message)) return null;
    throw error;
  }
}

function loadServiceWorkerAssets() {
  const appShellSource = readFileSync('sw-app-shell.js', 'utf8');
  const swSource = readFileSync('sw.js', 'utf8');
  const sandbox = {
    self: {
      addEventListener() {},
      skipWaiting() {},
      clients: { claim() {} },
      location: { origin: 'https://example.test' }
    },
    caches: { open() {}, keys() {}, match() {} },
    fetch() {},
    URL,
    Response,
    importScripts() {}
  };
  vm.runInNewContext(`${appShellSource}\n${swSource}\nthis.__APP_SHELL__ = APP_SHELL;`, sandbox, { filename: 'sw.js' });
  return sandbox.__APP_SHELL__;
}

test('service worker precache assets exist locally and are generated', () => {
  const localAssets = loadServiceWorkerAssets().filter((asset) => asset.startsWith('./'));
  const missing = localAssets
    .map((asset) => asset.replace(/^\.\//, ''))
    .filter((asset) => asset !== '' && !existsSync(asset));

  assert.equal(missing.length, 0, `Missing service worker assets: ${missing.join(', ')}`);
  assert.match(readFileSync('sw-app-shell.js', 'utf8'), /Generated by scripts\/generate-sw-app-shell\.js/);
  assert.match(readFileSync('package.json', 'utf8'), /"build:sw"/);
});

test('CSP removes unsafe script execution and adds hardening directives', () => {
  const source = readFileSync('server/index.js', 'utf8');
  assert.equal(source.includes("'unsafe-eval'"), false);
  assert.equal(source.includes('scriptSrc: ["\'self\'", "\'unsafe-inline\'"]'), false);
  assert.match(source, /scriptSrc:\s*\["'self'"\]/);
  assert.match(source, /scriptSrcAttr:\s*\["'none'"\]/);
  assert.match(source, /objectSrc:\s*\["'none'"\]/);
  assert.match(source, /frameAncestors:\s*\["'self'"\]/);
});

test('frontend/admin markup avoids inline JavaScript handlers', () => {
  const files = ['index.html', 'admin/index.html', 'admin/script.js'];
  for (const file of files) {
    const source = readFileSync(file, 'utf8');
    assert.equal(/\son[a-z]+\s*=/.test(source), false, `${file} should not include inline event handlers`);
    assert.equal(source.includes('.onclick'), false, `${file} should not assign onclick handlers`);
  }
});

test('CORS origins are explicit in production and environment-configurable', () => {
  const source = readFileSync('server/index.js', 'utf8');
  assert.match(source, /process\.env\.CORS_ORIGIN/);
  assert.match(source, /split\(','\)/);
  assert.match(source, /CORS_ORIGIN must be set in production/);
  assert.equal(source.includes("process.env.CORS_ORIGIN || 'https://triumph-laundry.vercel.app'"), false);
  assert.equal(source.includes('isAllowed || process.env.NODE_ENV'), false);
});

test('refresh tokens are hashed, rotated, tracked, and available via HttpOnly cookies', () => {
  const source = readFileSync('server/routes/auth.js', 'utf8');
  assert.match(source, /function hashRefreshToken/);
  assert.match(source, /createHash\('sha256'\)/);
  assert.match(source, /res\.cookie\(REFRESH_COOKIE_NAME, refreshToken/);
  assert.match(source, /httpOnly:\s*true/);
  assert.match(source, /sameSite:\s*'strict'/);
  assert.match(source, /token_family/);
  assert.match(source, /user_agent/);
  assert.match(source, /ip_address/);
  assert.match(source, /last_used_at/);
  assert.match(source, /refresh_token_reuse_detected/);
  assert.match(source, /INSERT INTO sessions[\s\S]*newRefreshTokenHash/);
  assert.match(source, /revoked_reason = 'rotated'/);
});

test('runtime databases, uploads, and production office documents are not tracked by git', () => {
  const files = execFileSync('git', ['ls-files'], { encoding: 'utf8' }).split('\n').filter(Boolean);
  const trackedRuntimeFiles = files.filter((file) =>
    /^server\/uploads\//.test(file) ||
    /^server\/.*\.db$/.test(file) ||
    /\.(xlsx|xls|pdf|pptx)$/i.test(file)
  );
  assert.equal(trackedRuntimeFiles.length, 0, `Tracked runtime/binary files: ${trackedRuntimeFiles.join(', ')}`);
});

test('schedule download route rejects query-string bearer tokens', () => {
  const source = readFileSync('server/routes/schedule.js', 'utf8');
  const downloadRoute = source.match(/router\.get\('\/admin\/schedule\/download\/:id'[\s\S]*?workbook\.xlsx\.write\(res\)\.then\(\(\) => res\.end\(\)\);/);

  assert.ok(downloadRoute, 'download route should exist');
  assert.match(downloadRoute[0], /authenticateToken/);
  assert.equal(downloadRoute[0].includes('req.query.token'), false);
  assert.equal(downloadRoute[0].includes('jsonwebtoken'), false);
});

test('admin schedule downloads use header-authenticated blob fetch with useful failure toast', () => {
  const source = readFileSync('admin/script.js', 'utf8');
  const downloadHandler = source.match(/window\._downloadSchedule = async function\(id\)[\s\S]*?\n\s*};/);

  assert.ok(downloadHandler, 'admin download handler should exist');
  assert.match(downloadHandler[0], /requestWithAuth\(`\/api\/admin\/schedule\/download\/\$\{id\}`\)/);
  assert.match(downloadHandler[0], /res\.blob\(\)/);
  assert.match(downloadHandler[0], /downloadBlob\(blob, filename\)/);
  assert.match(downloadHandler[0], /toast\('فشل تحميل الجدول: '\+err\.message,'error'\)/);
  assert.equal(downloadHandler[0].includes('?token='), false);
  assert.equal(downloadHandler[0].includes('window.open'), false);
});

test('catalogue data reads seed JSON into SQLite when no persisted row exists', (t) => {
  const Database = getOptionalBetterSqlite3();
  if (!Database) return t.skip('better-sqlite3 is not installed in this environment');
  const runMigrations = require('../server/db/migrate');
  const { _private: catalogue } = require('../server/routes/data-files');
  const db = new Database(':memory:');
  try {
    runMigrations(db);
    const expected = JSON.parse(readFileSync('data/chemicals.json', 'utf8'));

    const data = catalogue.getCatalogueData(db, 'chemicals');
    const row = db.prepare('SELECT payload FROM catalogue_data WHERE kind = ?').get('chemicals');

    assert.deepEqual(data, expected);
    assert.deepEqual(JSON.parse(row.payload), expected);
  } finally {
    db.close();
  }
});

test('catalogue data updates persisted SQLite payload and writes audit details', (t) => {
  const Database = getOptionalBetterSqlite3();
  if (!Database) return t.skip('better-sqlite3 is not installed in this environment');
  const runMigrations = require('../server/db/migrate');
  const { _private: catalogue } = require('../server/routes/data-files');
  const db = new Database(':memory:');
  try {
    runMigrations(db);
    const adminId = db.prepare('INSERT INTO admins (username, password_hash) VALUES (?, ?)').run('catalogue-admin', 'hash').lastInsertRowid;
    const replacement = [{ id: 'test-chemical', theme: 'blue', name: 'Test Chemical', code: 'TC-1' }];

    catalogue.replaceCatalogueData(db, 'chemicals', replacement, adminId);

    assert.deepEqual(catalogue.getCatalogueData(db, 'chemicals'), replacement);

    const audit = db.prepare('SELECT admin_id, action, details FROM audit_log ORDER BY id DESC LIMIT 1').get();
    assert.equal(audit.admin_id, adminId);
    assert.equal(audit.action, 'Update Catalogue Data');
    assert.deepEqual(JSON.parse(audit.details), {
      kind: 'chemicals',
      itemCount: 1,
      adminId
    });
  } finally {
    db.close();
  }
});

test('Vercel routes admin trailing slash and proxies API to serverless handler', () => {
  const vercel = JSON.parse(readFileSync('vercel.json', 'utf8'));
  const apiEntry = readFileSync('api/index.js', 'utf8');
  assert.ok(vercel.redirects?.some((r) => r.source === '/admin' && r.destination === '/admin/'));
  assert.ok(vercel.rewrites?.some((r) => r.source === '/api/(.*)' && r.destination === '/api'));
  assert.match(apiEntry, /require\('\.\.\/server\/index\.js'\)/);
});

test('migrations are tracked, checksum-protected, and runnable by npm script', () => {
  const source = readFileSync('server/db/migrate.js', 'utf8');
  assert.match(source, /Tracked migrations directory is missing/);
  assert.match(source, /createHash\('sha256'\)/);
  assert.match(source, /has changed since it was applied/);
  assert.equal(source.includes('copyFileSync'), false);
  assert.match(readFileSync('server/package.json', 'utf8'), /"migrate"/);
  assert.ok(existsSync('server/db/migrations/001_initial.sql'));
  assert.ok(existsSync('server/db/migrations/003_session_metadata.sql'));
});
